# Generated by Django 3.0.7 on 2020-07-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20200707_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to='item_pics'),
        ),
    ]
