# Generated by Django 3.0.7 on 2020-07-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200710_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1000),
        ),
    ]
