# Generated by Django 3.0.7 on 2020-07-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200711_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1000),
        ),
    ]
